name: bet_corner
description: Sports Betting Tips App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  get: ^4.6.5
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.1
  flutter_otp_text_field: ^1.1.1
  easy_search_bar: ^2.4.2
  line_awesome_flutter: ^2.0.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  google_sign_in: ^6.0.2
  firebase_database: ^10.1.0
  pay: ^1.1.0
  glassfy_flutter: ^1.3.8
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/splash_images/
    - assets/images/on_boarding_images/
    - assets/images/welcome_images/
    - assets/logo/
    - assets/images/forget_password/
    - assets/images/dashboard/
    - assets/images/profile/